#include "definitions.h"
const struct instr instructions[] = 
{
	{ 1, "NOP" },
	{ 2, "AJMP page0" },
	{ 3, "LJMP code addr" },
	{ 1, "RR A" },
	{ 1, "INC A" },
	{ 2, "INC iram addr" },
	{ 1, "INC @R0" },
	{ 1, "INC @R1" },
	{ 1, "INC R0" },
	{ 1, "INC R1" },
	{ 1, "INC R2" },
	{ 1, "INC R3" },
	{ 1, "INC R4" },
	{ 1, "INC R5" },
	{ 1, "INC R6" },
	{ 1, "INC R7" },
	{ 3, "JBC bit addr,reladdr" },
	{ 2, "ACALL page0" },
	{ 3, "LCALL code addr" },
	{ 1, "RRC A" },
	{ 1, "DEC A" },
	{ 2, "DEC iram addr" },
	{ 1, "DEC @R0" },
	{ 1, "DEC @R1" },
	{ 1, "DEC R0" },
	{ 1, "DEC R1" },
	{ 1, "DEC R2" },
	{ 1, "DEC R3" },
	{ 1, "DEC R4" },
	{ 1, "DEC R5" },
	{ 1, "DEC R6" },
	{ 1, "DEC R7" },
	{ 3, "JB bit addr,reladdr" },
	{ 2, "AJMP page1" },
	{ 1, "RET" },
	{ 1, "RL A" },
	{ 2, "ADD A,#data" },
	{ 2, "ADD A,iram addr" },
	{ 1, "ADD A,@R0" },
	{ 1, "ADD A,@R1" },
	{ 1, "ADD A,R0" },
	{ 1, "ADD A,R1" },
	{ 1, "ADD A,R2" },
	{ 1, "ADD A,R3" },
	{ 1, "ADD A,R4" },
	{ 1, "ADD A,R5" },
	{ 1, "ADD A,R6" },
	{ 1, "ADD A,R7" },
	{ 3, "JNB bit addr,reladdr" },
	{ 2, "ACALL page1" },
	{ 1, "RETI" },
	{ 1, "RLC A" },
	{ 2, "ADDC A,#data" },
	{ 2, "ADDC A,iram addr" },
	{ 1, "ADDC A,@R0" },
	{ 1, "ADDC A,@R1" },
	{ 1, "ADDC A,R0" },
	{ 1, "ADDC A,R1" },
	{ 1, "ADDC A,R2" },
	{ 1, "ADDC A,R3" },
	{ 1, "ADDC A,R4" },
	{ 1, "ADDC A,R5" },
	{ 1, "ADDC A,R6" },
	{ 1, "ADDC A,R7" },
	{ 2, "JC reladdr" },
	{ 2, "AJMP page2" },
	{ 2, "ORL iram addr,A" },
	{ 3, "ORL iram addr,#data" },
	{ 2, "ORL A,#data" },
	{ 2, "ORL A,iram addr" },
	{ 1, "ORL A,@R0" },
	{ 1, "ORL A,@R1" },
	{ 1, "ORL A,R0" },
	{ 1, "ORL A,R1" },
	{ 1, "ORL A,R2" },
	{ 1, "ORL A,R3" },
	{ 1, "ORL A,R4" },
	{ 1, "ORL A,R5" },
	{ 1, "ORL A,R6" },
	{ 1, "ORL A,R7" },
	{ 2, "JNC reladdr" },
	{ 2, "ACALL page2" },
	{ 2, "ANL iram addr,A" },
	{ 3, "ANL iram addr,#data" },
	{ 2, "ANL A,#data" },
	{ 2, "ANL A,iram addr" },
	{ 1, "ANL A,@R0" },
	{ 1, "ANL A,@R1" },
	{ 1, "ANL A,R0" },
	{ 1, "ANL A,R1" },
	{ 1, "ANL A,R2" },
	{ 1, "ANL A,R3" },
	{ 1, "ANL A,R4" },
	{ 1, "ANL A,R5" },
	{ 1, "ANL A,R6" },
	{ 1, "ANL A,R7" },
	{ 2, "JZ reladdr" },
	{ 2, "AJMP page3" },
	{ 2, "XRL iram addr,A" },
	{ 3, "XRL iram addr,#data" },
	{ 2, "XRL A,#data" },
	{ 2, "XRL A,iram addr" },
	{ 1, "XRL A,@R0" },
	{ 1, "XRL A,@R1" },
	{ 1, "XRL A,R0" },
	{ 1, "XRL A,R1" },
	{ 1, "XRL A,R2" },
	{ 1, "XRL A,R3" },
	{ 1, "XRL A,R4" },
	{ 1, "XRL A,R5" },
	{ 1, "XRL A,R6" },
	{ 1, "XRL A,R7" },
	{ 2, "JNZ reladdr" },
	{ 2, "ACALL page3" },
	{ 2, "ORL C,bit addr" },
	{ 1, "JMP @A+DPTR" },
	{ 2, "MOV A,#data" },
	{ 3, "MOV iram addr,#data" },
	{ 2, "MOV @R0,#data" },
	{ 2, "MOV @R1,#data" },
	{ 2, "MOV R0,#data" },
	{ 2, "MOV R1,#data" },
	{ 2, "MOV R2,#data" },
	{ 2, "MOV R3,#data" },
	{ 2, "MOV R4,#data" },
	{ 2, "MOV R5,#data" },
	{ 2, "MOV R6,#data" },
	{ 2, "MOV R7,#data" },
	{ 2, "SJMP reladdr" },
	{ 2, "AJMP page4" },
	{ 2, "ANL C,bit addr" },
	{ 1, "MOVC A,@A+PC" },
	{ 1, "DIV AB" },
	{ 3, "MOV iram addr,iram addr" },
	{ 2, "MOV iram addr,@R0" },
	{ 2, "MOV iram addr,@R1" },
	{ 2, "MOV iram addr,R0" },
	{ 2, "MOV iram addr,R1" },
	{ 2, "MOV iram addr,R2" },
	{ 2, "MOV iram addr,R3" },
	{ 2, "MOV iram addr,R4" },
	{ 2, "MOV iram addr,R5" },
	{ 2, "MOV iram addr,R6" },
	{ 2, "MOV iram addr,R7" },
	{ 3, "MOV DPTR,#data16" },
	{ 2, "ACALL page4" },
	{ 2, "MOV bit addr,C" },
	{ 1, "MOVC A,@A+DPTR" },
	{ 2, "SUBB A,#data" },
	{ 2, "SUBB A,iram addr" },
	{ 1, "SUBB A,@R0" },
	{ 1, "SUBB A,@R1" },
	{ 1, "SUBB A,R0" },
	{ 1, "SUBB A,R1" },
	{ 1, "SUBB A,R2" },
	{ 1, "SUBB A,R3" },
	{ 1, "SUBB A,R4" },
	{ 1, "SUBB A,R5" },
	{ 1, "SUBB A,R6" },
	{ 1, "SUBB A,R7" },
	{ 2, "ORL C,/bit addr" },
	{ 2, "AJMP page5" },
	{ 2, "MOV C,bit addr" },
	{ 1, "INC DPTR" },
	{ 1, "MUL AB" },
	{ 1, "???" },
	{ 2, "MOV @R0,iram addr" },
	{ 2, "MOV @R1,iram addr" },
	{ 2, "MOV R0,iram addr" },
	{ 2, "MOV R1,iram addr" },
	{ 2, "MOV R2,iram addr" },
	{ 2, "MOV R3,iram addr" },
	{ 2, "MOV R4,iram addr" },
	{ 2, "MOV R5,iram addr" },
	{ 2, "MOV R6,iram addr" },
	{ 2, "MOV R7,iram addr" },
	{ 2, "ANL C,/bit addr" },
	{ 2, "ACALL page5" },
	{ 2, "CPL bit addr" },
	{ 1, "CPL C" },
	{ 3, "CJNE A,#data,reladdr" },
	{ 3, "CJNE A,iram addr,reladdr" },
	{ 3, "CJNE @R0,#data,reladdr" },
	{ 3, "CJNE @R1,#data,reladdr" },
	{ 3, "CJNE R0,#data,reladdr" },
	{ 3, "CJNE R1,#data,reladdr" },
	{ 3, "CJNE R2,#data,reladdr" },
	{ 3, "CJNE R3,#data,reladdr" },
	{ 3, "CJNE R4,#data,reladdr" },
	{ 3, "CJNE R5,#data,reladdr" },
	{ 3, "CJNE R6,#data,reladdr" },
	{ 3, "CJNE R7,#data,reladdr" },
	{ 2, "PUSH iram addr" },
	{ 2, "AJMP page6" },
	{ 2, "CLR bit addr" },
	{ 1, "CLR C" },
	{ 1, "SWAP A" },
	{ 2, "XCH A,iram addr" },
	{ 1, "XCH A,@R0" },
	{ 1, "XCH A,@R1" },
	{ 1, "XCH A,R0" },
	{ 1, "XCH A,R1" },
	{ 1, "XCH A,R2" },
	{ 1, "XCH A,R3" },
	{ 1, "XCH A,R4" },
	{ 1, "XCH A,R5" },
	{ 1, "XCH A,R6" },
	{ 1, "XCH A,R7" },
	{ 2, "POP iram addr" },
	{ 2, "ACALL page6" },
	{ 2, "SETB bit addr" },
	{ 1, "SETB C" },
	{ 1, "DA" },
	{ 3, "DJNZ iram addr,reladdr" },
	{ 1, "XCHD A,@R0" },
	{ 1, "XCHD A,@R1" },
	{ 2, "DJNZ R0,reladdr" },
	{ 2, "DJNZ R1,reladdr" },
	{ 2, "DJNZ R2,reladdr" },
	{ 2, "DJNZ R3,reladdr" },
	{ 2, "DJNZ R4,reladdr" },
	{ 2, "DJNZ R5,reladdr" },
	{ 2, "DJNZ R6,reladdr" },
	{ 2, "DJNZ R7,reladdr" },
	{ 1, "MOVX A,@DPTR" },
	{ 2, "AJMP page7" },
	{ 1, "MOVX A,@R0" },
	{ 1, "MOVX A,@R1" },
	{ 1, "CLR A" },
	{ 2, "MOV A,iram addr" },
	{ 1, "MOV A,@R0" },
	{ 1, "MOV A,@R1" },
	{ 1, "MOV A,R0" },
	{ 1, "MOV A,R1" },
	{ 1, "MOV A,R2" },
	{ 1, "MOV A,R3" },
	{ 1, "MOV A,R4" },
	{ 1, "MOV A,R5" },
	{ 1, "MOV A,R6" },
	{ 1, "MOV A,R7" },
	{ 1, "MOVX @DPTR,A" },
	{ 2, "ACALL page7" },
	{ 1, "MOVX @R0,A" },
	{ 1, "MOVX @R1,A" },
	{ 1, "CPL A" },
	{ 2, "MOV iram addr,A" },
	{ 1, "MOV @R0,A" },
	{ 1, "MOV @R1,A" },
	{ 1, "MOV R0,A" },
	{ 1, "MOV R1,A" },
	{ 1, "MOV R2,A" },
	{ 1, "MOV R3,A" },
	{ 1, "MOV R4,A" },
	{ 1, "MOV R5,A" },
	{ 1, "MOV R6,A" },
	{ 1, "MOV R7,A" }
};
